FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements-ui.txt /app/requirements-ui.txt
RUN pip install --upgrade pip && pip install -r /app/requirements-ui.txt

COPY . /app

EXPOSE 8501

CMD ["streamlit", "run", "mtg_ui.py", "--server.address=0.0.0.0", "--server.port=8501"]
